export enum SubmissionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum SubmissionType {
  REGISTRATION_HANDICAP_USER = 'REGISTRATION_HANDICAP_USER',
  REGISTRATION_INSTITUTION = 'REGISTRATION_INSTITUTION',
  HANDICAP_ID_CARD = 'HANDICAP_ID_CARD',
  OTHER = 'OTHER',
}
