export enum DocumentType {
  PROOF_OF_HANDICAP = 'PROOF_OF_HANDICAP',
  CAREGIVER_PROOF = 'CAREGIVER_PROOF',
  IDENTITY_DOCUMENT = 'IDENTITY_DOCUMENT',
  INSTITUTION_DOC = 'INSTITUTION_DOC',
  OTHER = 'OTHER',
}
