FROM node:20-slim

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/frontend/package.json apps/frontend/package.json
COPY apps/backend/package.json apps/backend/package.json

RUN npm ci

COPY apps/frontend apps/frontend

EXPOSE 3000

CMD ["npm", "run", "-w", "apps/frontend", "dev"]