# Automated Backend CI workflow enforcing linting, type safety, testing, security auditing, and Docker build validation.

name: Backend CI

on:
  push:
    branches:
      - "feature/**"
      - "fix/**"
      - "hotfix/**"
      - "refactor/**"

    paths:
      - "apps/backend/**"
      - ".github/workflows/backend-ci.yml"

  pull_request:
    branches:
      - develop
      - main

    paths:
      - "apps/backend/**"

concurrency:
  group: backend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      # Currently we have a problem with the npm audit because of the apollo-server dep conflict will be fixed later
      # - name: Security audit
      #   run: npm audit --audit-level=high --workspace=apps/backend

      # This runs the TypeScript compiler in type-check mode (tsc --noEmit)
      # to catch type errors that may not appear during development or may be missed by ESLint rules.
      - name: Type Check
        run: npm run type-check --workspace=apps/backend

      - name: Lint
        run: npm run lint --workspace=apps/backend

      - name: Unit Tests with Coverage
        run: npm run test:coverage --workspace=apps/backend

      - name: Build
        run: npm run build --workspace=apps/backend

      # For later, once the production dockerfile is ready and we will be adding --cache-from or github actions cache for a better performance
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Build backend docker
      #   run: docker build -f apps/backend/Dockerfile -t sabilouna-backend:ci .
